language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Um0Jb+fKaPgzCzRvkxSnaWOH1v6AUU+CBBf+0lov5nVRZ1uAXYIXLHHNBZ/BPcunP/qRqOqKnny6YlSTsKMjzV+GGKUpjDozMtuWyjomXvXvlvn5iYIeokCcbAkHXMleuiQP8iZDQRO5t23CxyPI8jZ3g9TuXCGBijQFCEL8OFDOfFaVGyr5lUVdj0tnBySyAZQIsI75Z5jjrQqf1WW3M5coqquUXEVNu2n+gs/tfIvd3qz4EH5NJ7QR/419oDOaivFuWZtx3YF24fgSXkUfk6JUSVMA5DoDRjWMc5NJtyH+cmn/nyCjJXDE9VkchaKLNJDjtT/iUaX0A9G8uyUgP3Yb+fSJHfKdXds4GrxEHsR2dEsLXBQwUO1oESl0aaDzXXgo9Ehq/32cu8LLtkeHxvdm8wEec3X9DgMVfCd0zXFhE3BhvAcnLQxaRqnDim6qPRDeMtmiqh+bqkbHdCOkXCMTzds4yxsxOjDS82JkRaZYGaj1aCMibWbt/7bNgxJhhch+/uB5JWehM8Kjupq2ixB0RWLaVvQu1z9rRRIg03i6Q4b00tbJ7SNC6TvDuXiEPJMSBry8l+k7YM45FYY1jXLObGPNL0PSyv9YFdiTBJXYJLtB8K1GpWlKM8ETM4RFcV6hIG9qzSd4A8Fb81E0pOYJ+Kzh9/9KWBpOTpG+yhA=
  app: pandoracollection
